export { default as Home } from './Home'
export { default as Webcam } from './Webcam'
export { default as ImageDetection } from './ImageDetection'
export { default as TransferLearning } from './TransferLearning'
export { default as FaceMesh } from './FaceMesh'
export { default as SentimentAnalysis } from './SentimentAnalysis'
